# Generated by Django 6.0.4 on 2026-05-03 09:08

import django_field_encryption.fields
import django_field_encryption.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Uploaded file will be encrypted at rest', storage=django_field_encryption.storage.EncryptedFileStorage(), upload_to='documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ssn', django_field_encryption.fields.EncryptedCharField(help_text='Social Security Number (encrypted)')),
                ('notes', django_field_encryption.fields.EncryptedTextField(blank=True, help_text='Private notes (encrypted)')),
                ('preferences', django_field_encryption.fields.EncryptedJSONField(blank=True, default=dict, help_text='User preferences as JSON (encrypted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
