# Generated by Django 6.0.4 on 2026-05-05 11:27

import django_field_encryption.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ssn_hash',
            field=django_field_encryption.fields.BlindIndexField('ssn', db_index=True, default='', unique=True),
            preserve_default=False,
        ),
    ]
