# Generated by Django 6.0.4 on 2026-05-05 11:27

import django_field_encryption.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_profile_ssn_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Uploaded file will be encrypted at rest', storage=django_field_encryption.storage.EncryptedFileStorage, upload_to='documents/%Y/%m/'),
        ),
    ]
