# Generated by Django 6.0.4 on 2026-05-06 05:31

import django_field_encryption.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='encrypted_pages',
            field=django_field_encryption.fields.EncryptedIntegerField(default=0, help_text='Number of encrypted pages', strict=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=django_field_encryption.fields.EncryptedIntegerField(blank=True, help_text='Age (encrypted)', null=True, strict=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=django_field_encryption.fields.EncryptedDateField(blank=True, help_text='Date of birth (encrypted)', null=True, strict=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=django_field_encryption.fields.EncryptedDateTimeField(auto_now=True, strict=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=django_field_encryption.fields.EncryptedTextField(blank=True, help_text='Encrypted description', strict=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=django_field_encryption.fields.EncryptedDateTimeField(auto_now_add=True, strict=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=django_field_encryption.fields.EncryptedDateTimeField(auto_now_add=True, strict=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=django_field_encryption.fields.EncryptedEmailField(help_text='Encrypted email', max_length=254, strict=True),
        ),
    ]
